# Generated by Django 5.1.6 on 2025-03-04 18:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
