# Generated by Django 5.1.6 on 2025-03-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='text',
        ),
    ]
