# Generated by Django 5.1.6 on 2025-03-07 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_answervote_options_alter_questionvote_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='forum.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QuestionView',
                'verbose_name_plural': 'QuestionViews',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
